"""
ui_strings.py
Multi-Language UI Translations for AI Study Assistant
Supports: English (en), Hindi (hi), Telugu (te), Tamil (ta)
"""

SUPPORTED_LANGUAGES = {
    "en": {"name": "English", "native": "English", "speech_code": "en-US"},
    "hi": {"name": "Hindi", "native": "हिन्दी", "speech_code": "hi-IN"},
    "te": {"name": "Telugu", "native": "తెలుగు", "speech_code": "te-IN"},
    "ta": {"name": "Tamil", "native": "தமிழ்", "speech_code": "ta-IN"},
}

UI_STRINGS = {
    "en": {
        "app_title": "🎓 AI-Powered Study Assistant",
        "pipeline_caption": "Documents → Chunking → Embeddings (Sentence-Transformers) → FAISS Vector Store → Retriever → LLM Generation",
        "login_tab": "🔑 Login",
        "signup_tab": "📝 Sign Up",
        "login_header": "Welcome Back to AI Study Assistant",
        "signup_header": "Create Your Student Account",
        "username_label": "Username",
        "password_label": "Password",
        "fullname_label": "Full Name (Optional)",
        "login_button": "🚀 Log In",
        "signup_button": "✨ Create Account",
        "logout_button": "🚪 Logout",
        "logged_in_as": "Logged in as",
        "language_label": "🌐 Interface & Answer Language",
        "mode_label": "🤖 Assistant Answering Mode",
        "mode_hybrid": "Hybrid (Course Notes + ChatGPT General Knowledge)",
        "mode_strict": "Strict Course Notes Only (RAG)",
        "llm_header": "1. LLM Generation (Optional)",
        "api_key_label": "OpenAI API Key",
        "api_key_help": "Optional: Enter key for GPT-4o-mini generation. If omitted, app operates in Extractive Fallback Mode.",
        "api_key_active": "OpenAI API key configured (GPT-4o-mini active).",
        "fallback_mode_active": "No API key entered: running in Extractive Fallback Mode.",
        "retrieval_header": "2. Retrieval Settings",
        "top_k_label": "Retrieved Chunks (top_k)",
        "top_k_help": "Number of most similar text chunks retrieved from FAISS for answering.",
        "materials_header": "3. Study Materials",
        "upload_label": "Upload Notes, Textbooks, Slides",
        "upload_help": "Upload .txt or .pdf files containing your course notes.",
        "build_button": "🔨 Build / Rebuild",
        "sample_button": "⚡ Use Sample Notes",
        "upload_warning": "Please upload at least one .txt or .pdf file first, or click 'Use Sample Notes'.",
        "indexing_spinner": "Chunking, embedding, and indexing documents into FAISS...",
        "sample_spinner": "Indexing built-in sample Operating Systems notes...",
        "kb_status_header": "Knowledge Base Status",
        "status_ready": "Ready",
        "status_not_built": "Not Built (No documents indexed yet)",
        "files_badge": "Files",
        "chunks_badge": "Chunks",
        "model_badge": "Model",
        "indexed_files": "Indexed Files",
        "clear_chat_button": "💬 Clear Chat History",
        "clear_chat_warning": "⚠️ Delete all messages in the active chat?",
        "clear_chat_confirm": "✅ Delete Chats",
        "clear_chat_cancel": "❌ Cancel",
        "clear_kb_button": "🗑️ Clear Knowledge Base",
        "clear_warning": "⚠️ Clear all indexed chunks & knowledge base?",
        "clear_confirm": "✅ Yes, Clear KB",
        "clear_cancel": "❌ Cancel",
        "welcome_title": "👋 Welcome to your AI Study Assistant!",
        "welcome_step1": "1. Click **'⚡ Use Sample Notes'** in the sidebar to test immediately with college-level Operating Systems notes, or upload your own course materials (`.txt` or `.pdf`) and click **'🔨 Build / Rebuild'**.",
        "welcome_step2": "2. *(Optional)* Provide your **OpenAI API Key** in the sidebar for full synthesized answers with `gpt-4o-mini`. You can also ask **any general questions (like ChatGPT)**!",
        "welcome_step3": "3. Ask any question below or click the microphone for voice input — answers prioritize your study notes!",
        "try_asking": "Try asking questions like:",
        "sq_1": "What are the 4 Coffman conditions required for a deadlock?",
        "sq_2": "Compare processes and threads in terms of memory and context switching overhead.",
        "sq_3": "Explain the page fault handling sequence in demand paging.",
        "sq_4": "What is the capital of France and what is it famous for?",
        "chat_placeholder": "Ask anything from your notes or general knowledge (like ChatGPT)...",
        "searching_spinner": "Searching knowledge base and formulating grounded answer...",
        "assistant_badge": "📚 Study Assistant",
        "sources_label": "📎 Sources:",
        "read_aloud": "🔊 Read Aloud",
        "voice_input_tip": "🎙️ Click microphone to speak question in",
        "footer_credit": "AI-Powered Study Assistant · Built with LLMs + RAG",
    },
    "hi": {
        "app_title": "🎓 एआई अध्ययन सहायक (Study Assistant)",
        "pipeline_caption": "दस्तावेज़ → चंकिंग → एम्बेडिंग्स (MiniLM) → FAISS वेक्टर स्टोर → रिट्रीवर → LLM उत्तर निर्माण",
        "login_tab": "🔑 लॉगिन करें",
        "signup_tab": "📝 नया खाता बनाएं",
        "login_header": "एआई अध्ययन सहायक में आपका स्वागत है",
        "signup_header": "विद्यार्थी खाता बनाएं",
        "username_label": "उपयोगकर्ता नाम (Username)",
        "password_label": "पासवर्ड (Password)",
        "fullname_label": "पूरा नाम (वैकल्पिक)",
        "login_button": "🚀 लॉगिन करें",
        "signup_button": "✨ खाता बनाएं",
        "logout_button": "🚪 लॉगआउट",
        "logged_in_as": "उपयोगकर्ता",
        "language_label": "🌐 भाषा चुनें (Language)",
        "mode_label": "🤖 उत्तर देने का मोड",
        "mode_hybrid": "हाइब्रिड (कोर्स नोट्स + चैटजीपीटी सामान्य ज्ञान)",
        "mode_strict": "केवल कोर्स नोट्स (Strict RAG)",
        "llm_header": "1. LLM जनरेशन (वैकल्पिक)",
        "api_key_label": "OpenAI API Key",
        "api_key_help": "वैकल्पिक: GPT-4o-mini उत्तरों के लिए API की दर्ज करें।",
        "api_key_active": "OpenAI API Key सक्रिय (GPT-4o-mini चालू).",
        "fallback_mode_active": "कोई API की नहीं: एक्सट्रैक्टिव फ़ॉलबैक मोड सक्रिय है।",
        "retrieval_header": "2. रिट्रीवल सेटिंग्स",
        "top_k_label": "रिट्रीव किए गए चंक्स (top_k)",
        "top_k_help": "उत्तर के लिए खोजे जाने वाले चंक्स की संख्या।",
        "materials_header": "3. अध्ययन सामग्री (Notes)",
        "upload_label": "नोट्स, किताबें, स्लाइड्स अपलोड करें",
        "upload_help": "अपने कोर्स नोट्स (.txt या .pdf) फ़ाइलें अपलोड करें।",
        "build_button": "🔨 ज्ञानकोश बनाएं / अपडेट करें",
        "sample_button": "⚡ नमूना नोट्स लोड करें",
        "upload_warning": "कृपया पहले कम से कम एक .txt या .pdf फ़ाइल अपलोड करें।",
        "indexing_spinner": "दस्तावेजों को FAISS में इंडेक्स किया जा रहा है...",
        "sample_spinner": "ऑपरेटिंग सिस्टम्स के नमूना नोट्स लोड हो रहे हैं...",
        "kb_status_header": "ज्ञानकोश की स्थिति",
        "status_ready": "तैयार (Ready)",
        "status_not_built": "निर्मित नहीं (कोई दस्तावेज़ इंडेक्स नहीं)",
        "files_badge": "फ़ाइलें",
        "chunks_badge": "चंक्स",
        "model_badge": "मॉडल",
        "indexed_files": "इंडेक्स की गई फ़ाइलें",
        "clear_chat_button": "💬 चैट डिलीट करें (Clear Chat)",
        "clear_chat_warning": "⚠️ क्या आप वर्तमान चैट इतिहास हटाना चाहते हैं?",
        "clear_chat_confirm": "✅ चैट हटाएं",
        "clear_chat_cancel": "❌ रद्द करें",
        "clear_kb_button": "🗑️ ज्ञानकोश साफ़ करें",
        "clear_warning": "⚠️ क्या आप सभी इंडेक्स किए गए चंक्स हटाना चाहते हैं?",
        "clear_confirm": "✅ ज्ञानकोश हटाएं",
        "clear_cancel": "❌ रद्द करें",
        "welcome_title": "👋 आपके एआई अध्ययन सहायक में आपका स्वागत है!",
        "welcome_step1": "1. साइडबार में **'⚡ नमूना नोट्स लोड करें'** पर क्लिक करें या अपने नोट्स अपलोड करें।",
        "welcome_step2": "2. अपनी OpenAI API Key दर्ज करें। आप अपने नोट्स के अलावा **चैटजीपीटी की तरह कोई भी सामान्य प्रश्न** भी पूछ सकते हैं!",
        "welcome_step3": "3. नीचे कोई भी प्रश्न पूछें या माइक दबाकर बोलें!",
        "try_asking": "ये नमूना प्रश्न पूछकर देखें:",
        "sq_1": "डेडलॉक के लिए आवश्यक 4 कॉफमैन शर्तें क्या हैं?",
        "sq_2": "मेमोरी और कॉन्टेक्स्ट स्विचिंग के मामले में प्रोसेस और थ्रेड की तुलना करें।",
        "sq_3": "डिमांड पेजिंग में पेज फॉल्ट हैंडलिंग प्रक्रिया समझाइए।",
        "sq_4": "फ्रांस की राजधानी क्या है और वह किसके लिए प्रसिद्ध है?",
        "chat_placeholder": "अपने नोट्स या सामान्य ज्ञान से कुछ भी पूछें (ChatGPT की तरह)...",
        "searching_spinner": "उत्तर तैयार किया जा रहा है...",
        "assistant_badge": "📚 अध्ययन सहायक",
        "sources_label": "📎 स्रोत (Sources):",
        "read_aloud": "🔊 पढ़कर सुनाएं",
        "voice_input_tip": "🎙️ प्रश्न बोलने के लिए माइक पर क्लिक करें",
        "footer_credit": "एआई अध्ययन सहायक · LLM और RAG द्वारा संचालित",
    },
    "te": {
        "app_title": "🎓 AI స్టడీ అసిస్టెంట్ (Study Assistant)",
        "pipeline_caption": "డాక్యుమెంట్లు → చంకింగ్ → ఎంబెడ్డింగ్స్ (MiniLM) → FAISS వెక్టర్ స్టోర్ → రిట్రీవర్ → LLM సమాధానం",
        "login_tab": "🔑 లాగిన్",
        "signup_tab": "📝 ఖాతా తెరవండి",
        "login_header": "AI స్టడీ అసిస్టెంట్‌కి స్వాగతం",
        "signup_header": "విద్యార్థి ఖాతాను సృష్టించండి",
        "username_label": "యూజర్‌నేమ్ (Username)",
        "password_label": "పాస్‌వర్డ్ (Password)",
        "fullname_label": "పూర్తి పేరు (ఐచ్ఛికం)",
        "login_button": "🚀 లాగిన్ అవ్వండి",
        "signup_button": "✨ ఖాతా సృష్టించండి",
        "logout_button": "🚪 లాగౌట్",
        "logged_in_as": "లాగిన్ అయిన యూజర్",
        "language_label": "🌐 భాషను ఎంచుకోండి (Language)",
        "mode_label": "🤖 అసిస్టెంట్ మోడ్",
        "mode_hybrid": "హైబ్రిడ్ (కోర్సు నోట్స్ + ChatGPT జనరల్ నాలెడ్జ్)",
        "mode_strict": "కోర్సు నోట్స్ మాత్రమే (Strict RAG)",
        "llm_header": "1. LLM జనరేషన్ (ఐచ్ఛికం)",
        "api_key_label": "OpenAI API Key",
        "api_key_help": "ఐచ్ఛికం: GPT-4o-mini సమాధానాల కోసం API కీని నమోదు చేయండి.",
        "api_key_active": "OpenAI API Key సక్రియంగా ఉంది (GPT-4o-mini ఆన్‌లో ఉంది).",
        "fallback_mode_active": "API కీ లేదు: ఎక్స్‌ట్రాక్టివ్ ఫాల్‌బ్యాక్ మోడ్ పనిచేస్తోంది.",
        "retrieval_header": "2. రిట్రీవల్ సెట్టింగ్స్",
        "top_k_label": "తీసుకున్న చంక్స్ (top_k)",
        "top_k_help": "సమాధానం కోసం తీసుకోబడిన భాగాల సంఖ్య.",
        "materials_header": "3. స్టడీ మెటీరియల్స్ (Notes)",
        "upload_label": "నోట్స్, పుస్తకాలు, స్లైడ్‌లను అప్‌లోడ్ చేయండి",
        "upload_help": "మీ కోర్సు నోట్స్ (.txt లేదా .pdf) ఫైళ్లను అప్‌లోడ్ చేయండి.",
        "build_button": "🔨 నాలెడ్జ్ బేస్ నిర్మించండి",
        "sample_button": "⚡ శాంపిల్ నోట్స్ వాడండి",
        "upload_warning": "దయచేసి ఒక .txt లేదా .pdf ఫైల్‌ని అప్‌లోడ్ చేయండి.",
        "indexing_spinner": "డాక్యుమెంట్లను FAISS లోకి ఇండెక్స్ చేస్తోంది...",
        "sample_spinner": "శాంపిల్ నోట్స్‌ని ఇండెక్స్ చేస్తోంది...",
        "kb_status_header": "నాలెడ్జ్ బేస్ స్థితి",
        "status_ready": "సిద్ధంగా ఉంది (Ready)",
        "status_not_built": "నిర్మించబడలేదు (డాక్యుమెంట్లు లేవు)",
        "files_badge": "ఫైళ్లు",
        "chunks_badge": "చంక్స్",
        "model_badge": "మోడల్",
        "indexed_files": "ఇండెక్స్ చేయబడిన ఫైళ్లు",
        "clear_chat_button": "💬 చాట్ డిలీట్ చేయండి (Clear Chat)",
        "clear_chat_warning": "⚠️ చాట్ సంభాషణను పూర్తిగా డిలీట్ చేయాలనుకుంటున్నారా?",
        "clear_chat_confirm": "✅ చాట్ తొలగించు",
        "clear_chat_cancel": "❌ రద్దు చేయి",
        "clear_kb_button": "🗑️ నాలెడ్జ్ బేస్ క్లియర్ చేయండి",
        "clear_warning": "⚠️ నాలెడ్జ్ బేస్ డేటాను క్లియర్ చేయాలనుకుంటున్నారా?",
        "clear_confirm": "✅ అవును, క్లియర్ చేయి",
        "clear_cancel": "❌ రద్దు చేయి",
        "welcome_title": "👋 మీ AI స్టడీ అసిస్టెంట్‌కి స్వాగతం!",
        "welcome_step1": "1. సైడ్‌బార్‌లో **'⚡ శాంపిల్ నోట్స్ వాడండి'** క్లిక్ చేయండి లేదా మీ నోట్స్ అప్‌లోడ్ చేయండి.",
        "welcome_step2": "2. OpenAI API Key నమోదు చేయండి. నోట్స్తో పాటు **ChatGPT లాగా ఏదైనా జనరల్ ప్రశ్న** కూడా అడగవచ్చు!",
        "welcome_step3": "3. దిగువన ప్రశ్న అడగండి లేదా మైక్ క్లిక్ చేసి మాట్లాడండి!",
        "try_asking": "ఈ ప్రశ్నలను అడిగి చూడండి:",
        "sq_1": "డెడ్‌లాక్ ఏర్పడటానికి అవసరమైన 4 కాఫ్‌మ్యాన్ పరిస్థితులు ఏమిటి?",
        "sq_2": "మెమరీ మరియు కాంటెక్స్ట్ స్విచ్చింగ్ పరంగా ప్రాసెస్ మరియు థ్రెడ్‌లను పోల్చండి.",
        "sq_3": "డిమాండ్ పేజింగ్‌లో పేజ్ ఫాల్ట్ హ్యాండ్లింగ్ విధానాన్ని వివరించండి.",
        "sq_4": "ఫ్రాన్స్ రాజధాని ఏది మరియు అది దేనికి ప్రసిద్ధి చెందింది?",
        "chat_placeholder": "మీ నోట్స్ లేదా ChatGPT లాగా ఏదైనా జనరల్ ప్రశ్న అడగండి...",
        "searching_spinner": "సమాధానం రూపొందిస్తోంది...",
        "assistant_badge": "📚 స్టడీ అసిస్టెంట్",
        "sources_label": "📎 మూలాలు (Sources):",
        "read_aloud": "🔊 చదివి వినిపించు",
        "voice_input_tip": "🎙️ ప్రశ్న మాట్లాడటానికి మైక్ క్లిక్ చేయండి",
        "footer_credit": "AI స్టడీ అసిస్టెంట్ · LLM & RAG ఆధారితం",
    },
    "ta": {
        "app_title": "🎓 AI படிப்பு உதவியாளர் (Study Assistant)",
        "pipeline_caption": "ஆவணங்கள் → துண்டாக்குதல் → உட்பொதித்தல் (MiniLM) → FAISS திசையன் சேமிப்பகம் → மீட்பான் → LLM பதில்",
        "login_tab": "🔑 உள்நுழைக",
        "signup_tab": "📝 கணக்கு தொடங்கு",
        "login_header": "AI படிப்பு உதவியாளருக்கு நல்வரவு",
        "signup_header": "மாணவர் கணக்கை உருவாக்கவும்",
        "username_label": "பயனர்பெயர் (Username)",
        "password_label": "கடவுச்சொல் (Password)",
        "fullname_label": "முழு பெயர் (விருப்பத்திற்குரியது)",
        "login_button": "🚀 உள்நுழைக",
        "signup_button": "✨ கணக்கு உருவாக்கு",
        "logout_button": "🚪 வெளியேறு",
        "logged_in_as": "உள்நுழைந்துள்ள பயனர்",
        "language_label": "🌐 மொழியைத் தேர்ந்தெடுக்கவும் (Language)",
        "mode_label": "🤖 உதவியாளர் முறை (Mode)",
        "mode_hybrid": "ஹைப்ரிட் (பாடக் குறிப்புகள் + ChatGPT பொது அறிவு)",
        "mode_strict": "பாடக் குறிப்புகள் மட்டும் (Strict RAG)",
        "llm_header": "1. LLM தலைமுறை (விருப்பத்திற்குரியது)",
        "api_key_label": "OpenAI API Key",
        "api_key_help": "விருப்பத்திற்குரியது: GPT-4o-mini பதில்களுக்கு API சாவியை உள்ளிடவும்.",
        "api_key_active": "OpenAI API Key இயக்கத்தில் உள்ளது (GPT-4o-mini செயலில் உள்ளது).",
        "fallback_mode_active": "API சாவி இல்லை: பிரித்தெடுத்தல் முறை செயலில் உள்ளது.",
        "retrieval_header": "2. மீட்பு அமைப்புகள்",
        "top_k_label": "மீட்கப்பட்ட துண்டுகள் (top_k)",
        "top_k_help": "பதிலுக்காக FAISS-லிருந்து எடுக்கப்படும் தொடர்புடைய துண்டுகளின் எண்ணிக்கை.",
        "materials_header": "3. படிப்புப் பொருட்கள் (Notes)",
        "upload_label": "குறிப்புகள், புத்தகங்கள், ஸ்லைடுகளைப் பதிவேற்றவும்",
        "upload_help": "உங்கள் பாடக் குறிப்புகளை (.txt அல்லது .pdf) பதிவேற்றவும்.",
        "build_button": "🔨 அறிவுத்தளத்தை உருவாக்கு",
        "sample_button": "⚡ மாதிரி குறிப்புகளைப் பயன்படுத்து",
        "upload_warning": "தயவுசெய்து ஒரு .txt அல்லது .pdf கோப்பை பதிவேற்றவும்.",
        "indexing_spinner": "ஆவணங்கள் FAISS-ல் அட்டவணைப்படுத்தப்படுகின்றன...",
        "sample_spinner": "மாதிரிக் குறிப்புகள் அட்டவணைப்படுத்தப்படுகின்றன...",
        "kb_status_header": "அறிவுத்தள நிலை",
        "status_ready": "தயாராக உள்ளது (Ready)",
        "status_not_built": "உருவாக்கப்படவில்லை (ஆவணங்கள் இல்லை)",
        "files_badge": "கோப்புகள்",
        "chunks_badge": "துண்டுகள்",
        "model_badge": "மாதிரி",
        "indexed_files": "அட்டவணைப்படுத்தப்பட்ட கோப்புகள்",
        "clear_chat_button": "💬 அரட்டையை நீக்கு (Clear Chat)",
        "clear_chat_warning": "⚠️ தற்போதைய அரட்டை செய்திகளை நீக்க விரும்புகிறீர்களா?",
        "clear_chat_confirm": "✅ அரட்டையை நீக்கு",
        "clear_chat_cancel": "❌ ரத்துசெய்",
        "clear_kb_button": "🗑️ அறிவுத்தளத்தை அழி",
        "clear_warning": "⚠️ அனைத்து துண்டுகளையும் அழிக்க விரும்புகிறீர்களா?",
        "clear_confirm": "✅ அறிவுத்தளத்தை அழி",
        "clear_cancel": "❌ ரத்துசெய்",
        "welcome_title": "👋 உங்கள் AI படிப்பு உதவியாளருக்கு நல்வரவு!",
        "welcome_step1": "1. பக்கவாட்டுப் பட்டியில் **'⚡ மாதிரி குறிப்புகளைப் பயன்படுத்து'** என்பதை கிளிக் செய்யவும் அல்லது உங்கள் குறிப்புகளைப் பதிவேற்றவும்.",
        "welcome_step2": "2. உங்கள் OpenAI API சாவியை உள்ளிடவும். உங்கள் குறிப்புகளுடன் **ChatGPT போன்ற பொதுவான கேள்விகளையும்** கேட்கலாம்!",
        "welcome_step3": "3. கீழே ஏதேனும் கேள்வியைக் கேட்கவும் அல்லது மைக்ரோஃபோனைக் கிளிக் செய்து பேசவும்!",
        "try_asking": "இந்த மாதிரிக் கேள்விகளைக் கேட்டுப் பாருங்கள்:",
        "sq_1": "டெட்லாக் (Deadlock) ஏற்படுவதற்குத் தேவையான 4 காஃப்மேன் நிபந்தனைகள் யாவை?",
        "sq_2": "நினைவகம் மற்றும் சூழல் மாறுதல் அடிப்படையில் செயல்முறை (Process) மற்றும் த்ரெட் (Thread) ஆகியவற்றை ஒப்பிடுக.",
        "sq_3": "டிமாண்ட் பேஜிங்கில் பக்கப் பிழை (Page Fault) கையாளும் வரிசையை விளக்குக.",
        "sq_4": "பிரான்சின் தலைநகரம் எது மற்றும் அது எதற்கு பிரபலமானது?",
        "chat_placeholder": "உங்கள் குறிப்புகள் அல்லது ChatGPT போன்ற பொதுவான கேள்விகளைக் கேளுங்கள்...",
        "searching_spinner": "அறிவுத்தளத்தில் தேடி பதில் தயாரிக்கப்படுகிறது...",
        "assistant_badge": "📚 படிப்பு உதவியாளர்",
        "sources_label": "📎 மூலங்கள் (Sources):",
        "read_aloud": "🔊 வாசித்துக் காட்டு",
        "voice_input_tip": "🎙️ கேள்வி பேச மைக்கை கிளிக் செய்யவும்",
        "footer_credit": "AI படிப்பு உதவியாளர் · LLM மற்றும் RAG மூலம் உருவாக்கப்பட்டது",
    },
}


def t(key: str, lang: str = "en") -> str:
    """Retrieve translated string for given key and language code."""
    lang_dict = UI_STRINGS.get(lang, UI_STRINGS["en"])
    return lang_dict.get(key, UI_STRINGS["en"].get(key, key))
